---
title: "AutohierarchyM: automatic hierarchy construction using marker genes I"
output: html_notebook
---

```{r, message=FALSE, warning=FALSE, results="hide"}
#devtools::install_github("khodosevichlab/CellAnnotatoR")
#devtools::install_github("hms-dbmi/sccore", ref="dev", force=TRUE)
#devtools::install_github('YuLab-SMU/ggtree') #package ‘aplot’ is not available (for R version 3.5.1)
#install.packages("pROC") #For AUC
#devtools::load_all("~/CellAnnotatoR") # Every time one changes the functions in R folder, one needs to reload the package.
```

```{r, message=FALSE, warning=FALSE, results="hide"}
library(sccore)
library(ggplot2)
library(magrittr)
library(Matrix)
library(pbapply)
library(dplyr)
library(pagoda2)
library(readr)
library(CellAnnotatoR)

theme_set(theme_bw())
```


# Automatic hierarchy construction using marker genes II

### Import the annontation and uncertainty data
```{r}
#here annotation is a list, each element represents the annotation of all cells at on hierarchical level
ann.by.level.coll2.g <- readRDS("~/CellAnnotatoR/notebooks/annbylevels/ann.by.level.coll2.g.rds")
ann.by.level.auto.g <- readRDS("~/CellAnnotatoR/notebooks/annbylevels/ann.by.level.auto.g.rds")
ann.by.level.man.g <- readRDS("~/CellAnnotatoR/notebooks/annbylevels/ann.by.level.man.g.rds")
ann.by.level.pre.g <- readRDS("~/CellAnnotatoR/notebooks/annbylevels/ann.by.level.pre.g.rds")

#here uncertainty is also a list of lists, each main element is one hierarchical level; at each hierarchical level, there is a sublist, which contains 3 elements: positive, negative and coverage uncertainty.
unc.per.cell.coll2.g <- readRDS("~/CellAnnotatoR/notebooks/uncertainty/unc.per.cell.coll2.g.rds")
unc.per.cell.man.g <- readRDS("~/CellAnnotatoR/notebooks/uncertainty/unc.per.cell.man.g.rds")
unc.per.cell.auto.g <- readRDS("~/CellAnnotatoR/notebooks/uncertainty/unc.per.cell.auto.g.rds")
unc.per.cell.pre.g <- readRDS("~/CellAnnotatoR/notebooks/uncertainty/unc.per.cell.pre.g.rds")
```

### Prepare the uncertainty data (as "trait") for plotUncHierarchy()
```{r}
unc.trait.coll2 <- uncToTreeTrait(unc.per.cell.coll2.g, ann.by.level.coll2.g)
  saveRDS(unc.trait.coll2, file="~/plothierarhy/notebooks/traitfiles/unc.trait.coll2.rds")
unc.trait.man <- uncToTreeTrait(unc.per.cell.man.g, ann.by.level.man.g)
  saveRDS(unc.trait.coll2, file="~/plothierarhy/notebooks/traitfiles/unc.trait.man.rds")
unc.trait.auto <- uncToTreeTrait(unc.per.cell.auto.g, ann.by.level.auto.g)
  saveRDS(unc.trait.coll2, file="~/plothierarhy/notebooks/traitfiles/unc.trait.auto.rds")
unc.trait.pre <- uncToTreeTrait(unc.per.cell.pre.g, ann.by.level.pre.g)
  saveRDS(unc.trait.coll2, file="~/plothierarhy/notebooks/traitfiles/unc.trait.pre.rds")
```

